[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor -L defmt --chip esp32c3"
[env]

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tdefmt.x",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]
